version: 2
updates:
- directory: /
  open-pull-requests-limit: 1
  package-ecosystem: npm
  rebase-strategy: auto
  schedule:
    interval: daily
  commit-message:
    prefix: chore
    include: scope
